[server.http]
port=8080
host="0.0.0.0"
target="local"

[server.https]
port=8083
host="0.0.0.0"
target="local"
ssl=true
cert="etc/selfsigned.cert"
key="etc/selfsigned.key"

[target.local]
host="localhost"
port=8090
